---
- name: app1 playbook
  hosts: all
  tasks:
  
- name: Copy app1comp1 to all the servers  
  hosts: all
  roles:
    - app1comp1

- name: Copy app1comp2 to Win2012 Server  
  hosts: Win2012
  roles:
    - app1comp2

